### ISSUE TITLE
Profiling async functions

### ISSUE THREAD

**Issue by Daenyth** [rkern/line_profiler#103]
I have some `async def` functions in my codebase, and when I run line_profiler over my script, the results come back blank with short timing for them. How can I accurately profile them?

**Comment by xavieryao** [comment]
Perhaps this will help? https://github.com/rkern/line_profiler/pull/75 Haven't tried myself.

**Comment by xavieryao** [comment]
@Daenyth It works perfectly.

**Comment by caethan** [comment]
#75 merged into master.
