### ISSUE TITLE
pstats gives "ValueError: bad marshal data (unknown type code)"

### ISSUE THREAD

**Issue by certik** [rkern/line_profiler#117]
This works:
```
$ python -m line_profiler my.lprof > log
```
But this fails:
```
$ python -m pstats my.lprof 
ValueError: bad marshal data (unknown type code)
Welcome to the profile statistics browser.
%
```
It should work according to the [documentation](https://github.com/rkern/line_profiler/blob/df8dfc88049effeac5fb77830bc9456052ea5c33/README.rst#kernprof):
```
$ python -m pstats script_to_profile.py.prof
```

I also tried `pyprof2calltree` and it gives the same exception.

I am using Python 3.6 with Conda 4.5.0 on Ubuntu 16.04.

**Comment by rkern** [comment]
No, the `.lprof` files from the line-profiler are not the same thing as the `.prof` files. The latter are from the regular function profiler, not the line-profiler.

> kernprof also works with cProfile, its third-party incarnation lsprof, or the pure-Python profile module depending on what is available.
