### ISSUE TITLE
Explicitly check for Python 3 for deciding on `builtins` import

### ISSUE THREAD

**Issue by rkern** [rkern/line_profiler#12]
The [`future`](https://pypi.python.org/pypi/future) package provides a `builtins` module that masquerades as a Python 3 `builtins` module, but it is a read-only namespace. Injecting into it doesn't affect the actual `__builtin__` namespace.

**Comment by rockymeza** [comment]
perhaps the try/except block could be reversed to have the Python 2 `__builtin__` import first?

**Comment by altarmobile** [comment]
the future d 0.14.3 was installed. it is anaconda 2.7, and the package is running on Mac OS X 10.10.3

moreover, 
in ipython,

%load_ext line_profiler

from primes import primes

In [4]: from primes import primes
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-4-1309b64e0396> in <module>()
----> 1 from primes import primes

/Users/Retina/Developer/Python/analysisPythonCode/primes.py in <module>()
      6 """
      7
----> 8 @profile
      9 def primes(n):
     10     if n==2:

NameError: name 'profile' is not defined
