### ISSUE TITLE
Export stats to pandas dataframe

### ISSUE THREAD

**Issue by JoergVanAken** [rkern/line_profiler#130]
I really like the line profiler. To make the results easier to understand I added the feature to export the result to a pandas dataframe. In combination with two small extra funtions it is very easy to get an overview where the time is spent a to go into details. Please let me know if you are interested in this so that I can make the code available.

![image](https://user-images.githubusercontent.com/38978810/43396683-9a2ced84-9402-11e8-897d-4194db55b66a.png)

**Comment by caethan** [comment]
Very interesting, but probably not something we're going to pull in the main repo.
