### ISSUE TITLE
How to select timer unit?

### ISSUE THREAD

**Issue by kylekeppler** [rkern/line_profiler#136]
I see that #98 adds the ability to set the unit for the timer used. How do I input that?

I am currently doing:

    kernprof -l myscript.py
    
then
  
    python -m line_profiler myscript.py.lprof

**Comment by rkaplan** [comment]
I have the same request. It looks like that PR only adds support for selecting timer units using the Jupyter notebook magic command. Maybe @caethan or @rkern can add support for this when using `python -m line_profiler ...` as well?

**Comment by caethan** [comment]
Sorry, currently magic command only.  I don't have time to add support for using it from the command line, but I'd be happy to look at pull requests to do so.
