### ISSUE TITLE
Error when loading profile data: cPickle.UnpicklingError: invalid load key

### ISSUE THREAD

**Issue by rbu** [rkern/line_profiler#14]
Current version on PyPI (1.0) errors out when loading the pickled data. This is a virtualenv'ed Python on Fedora 20.

``` bash
(virtualenv)rbu@saul ~ $ cat bla.py 
@profile
def hello():
    print('Hello, world!')

hello()


(virtualenv)rbu@saul ~ $ kernprof --line-by-line bla.py
Hello, world!
Wrote profile results to bla.py.lprof

(virtualenv)rbu@saul ~ $ python -m line_profiler bla.py
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/rbu/devel/virtualenvs/virtualenv/lib/python2.7/site-packages/line_profiler.py", line 394, in <module>
    main()
  File "/home/rbu/devel/virtualenvs/virtualenv/lib/python2.7/site-packages/line_profiler.py", line 390, in main
    lstats = load_stats(args[0])
  File "/home/rbu/devel/virtualenvs/virtualenv/lib/python2.7/site-packages/line_profiler.py", line 380, in load_stats
    return pickle.load(f)
cPickle.UnpicklingError: invalid load key, '@'.

(virtualenv)1 rbu@saul ~ $ python --version
Python 2.7.5

(virtualenv)rbu@saul ~ $ hexdump -C  bla.py.lprof    
00000000  80 02 63 5f 6c 69 6e 65  5f 70 72 6f 66 69 6c 65  |..c_line_profile|
00000010  72 0a 4c 69 6e 65 53 74  61 74 73 0a 71 01 29 81  |r.LineStats.q.).|
00000020  71 02 7d 71 03 28 55 04  75 6e 69 74 71 04 47 3e  |q.}q.(U.unitq.G>|
00000030  b0 c6 f7 a0 b5 ed 8d 55  07 74 69 6d 69 6e 67 73  |.......U.timings|
00000040  71 05 7d 71 06 55 06 62  6c 61 2e 70 79 71 07 4b  |q.}q.U.bla.pyq.K|
00000050  01 55 05 68 65 6c 6c 6f  71 08 87 5d 71 09 4b 03  |.U.helloq..]q.K.|
00000060  4b 01 4b 1e 87 71 0a 61  73 75 62 2e              |K.K..q.asub.|
0000006c
```

**Comment by Beastrock** [comment]
FileNotFoundError: [Errno 2] No such file or directory: 'main.py.lprof'

**Comment by rkern** [comment]
That says that there is no file `main.py.lprof`. Did you misspell the name of the file? Is the file there?

**Comment by pavelkomarov** [comment]
It is not working. I tried python -m line_profiler test.py, and I get the UnplicklingError. I tried python -m line_profiler test.py.lprof, and I get an error that the file does not exist. If I save test.py as test.py.lprof and run the same command, it's back to a pickling error.

**Comment by rkern** [comment]
`python -m line_profiler` loads a profiler dump file to view it. Use `kernprof --line-by-line test.py` to actually profile `test.py`. That will create a `test.py.lprof` file. Run `python -m line_profiler test.py.lprof` to view it. If you are still having trouble, please reread the README. If you are still having trouble after that, please copy-paste what you tried (and tell me in a sentence what you are trying to accomplish; e.g. profile the code, view the profile dump, etc.) and the full error messages that you get. @rbu's original post here is a good example.

**Comment by pavelkomarov** [comment]
That works. Why did you design it such that python -m line_profiler test.py doesn't actually do the testing?

**Comment by pavelkomarov** [comment]
Now I am trying to profile unit tests and profile the code my unit tests are using. But if I call kernprof -l -v TestThing.py, no tests are run.
