### ISSUE TITLE
Kernprof output is incomplete

### ISSUE THREAD

**Issue by ReddyKilowatt** [rkern/line_profiler#16]
After running kernprof -l myscript.py, 
then python -m line_profiler myscript.py.lprof

this is all that is displayed
Timer unit: 3.30314e-07 s

I'm using Python 2.7.6 32-Bit on Windows 7 Pro

**Comment by rkern** [comment]
Did you annotate a function to profile using the `@profile` decorator? Please provide a complete, self-contained `myscript.py` that demonstrates the problem.

**Comment by ReddyKilowatt** [comment]
No. 

This 
"It has been written to be used as a decorator, so in your script, you can decorate any function you want to profile with @profile."
needs to be changed to "MUST", instead of "can"

**Comment by ReddyKilowatt** [comment]
The profiling seems to be working now, as the program execution is now much slower.
Thanks!
