### ISSUE TITLE
Explain what the statement "kernprof" is, in the documentation

### ISSUE THREAD

**Issue by Jakobhenningjensen** [rkern/line_profiler#181]
In the documentation it is stated that you can run the following 

`kernprof -l script_to_profile.py`

but what is kernprof? Is it the python-script named "kernprof.py", and should that be added to PATH ?
A more in-depth explanation of what is would be great for new-commers.

**Comment by rkern** [comment]
This repository is unmaintained. Please go to https://github.com/pyutils/line_profiler

In any case, the `kernprof` script will be installed (without the `.py` extension) through the normal installation process that is described in the `README`.

**Comment by Jakobhenningjensen** [comment]
Thank you for the repsonse (I actually thought I posted the question in the "real" repo).

In the the `README` I do not seem to find how to use the profiler. Yes, the line `kernprof -l script_to_profile.py` is there but not what `kernprof` here refers to. Running that line gives the `kernprof command not found`. The `kernprof` script is mentioned, and assuming it is the `kernprof.py` in the repo then you would need to clone the repo to use it (also, how would you use that script ?).

There might be some implicit steps which I am missing, but... how do you go from a fresh install of the packages to use it? I have read the `README` several times

**Comment by rkern** [comment]
After following the installation instructions, a `kernprof` script (with no extension) should have been installed where Python executable scripts normally get installed, whatever that happens to be for your Python installation. If you are running from the current release, there may be a bug with that; I have not followed the development since handing it over.

**Comment by Jakobhenningjensen** [comment]
Okay, that makes more sense  - I will open an issue on the other repo then.
