### ISSUE TITLE
install windows on python 3.8 pip 20.1.1

### ISSUE THREAD

**Issue by adir1661** [rkern/line_profiler#183]
hello i am trying to install this on windows with pip version: 

`pip 20.1.1 from c:\...\python38\lib\site-packages\pip (python 3.8)`

and i cant figure out the command given in the documentation for windows shell... 

> Note: As of version 2.1.2, pip install line_profiler does not work. Please install as follows until it is fixed in the next release:
> 
> ```
> git clone https://github.com/rkern/line_profiler.git
> find line_profiler -name '*.pyx' -exec cython {} \;
> cd line_profiler
> pip install . --user
> ```

the command above does work and when i run it on git bash i also get 
`find: ‘cython’: No such file or directory`

**Comment by rkern** [comment]
I no longer maintain `line_profiler`. Please visit https://github.com/pyutils/line_profiler
