### ISSUE TITLE
TypeError: main() takes exactly 1 argument (0 given)

### ISSUE THREAD

**Issue by HaveF** [rkern/line_profiler#2]
I use [this script](https://gist.github.com/danriti/8015889/raw/caf2297984f3745a446b2410c7af9b20a70875a1/example.py) to profile.

But when I run kernprof, get the error like this:

```
R:\>kernprof -l example.py
Traceback (most recent call last):
  File "C:\Anaconda\Scripts\kernprof-script.py", line 9, in <module>
    load_entry_point('line-profiler==1.0', 'console_scripts', 'kernprof')()
TypeError: main() takes exactly 1 argument (0 given)
```

I use python(anaconda) on windows x64,  and have installed line-profiler 1.0 already.

Can you give me some advises?

**Comment by peachykeenirene** [comment]
Hi, I'm having the same issue. How did you solve it?
