### ISSUE TITLE
"1.0b2" hardcoded into kernprof.py?

### ISSUE THREAD

**Issue by ianozsvald** [rkern/line_profiler#22]
Hi Robert. I'm having trouble getting kernprof to run on a Windows box (<sigh>). The first confusing bit was `kernprof --version` showing `1.0b2` when I'd built from source, I was expecting something like `1.0` (having gone via `pip` and thinking it was an old release).

Looking at `kernprof.py`'s OptionParser it looks like `1.0b2` is hard-coded. Is that a minor oversight? Or does the `1.0` code live somewhere else? I wanted to rule out any Python 3 issues.
https://github.com/rkern/line_profiler/blob/master/kernprof.py#L152

Regarding my Windows issue, that's for Python 3.4 via Anaconda on a recent Windows, I'll file a report for that in the morning if we can't get it fixed (it segfaults, I see someone else posted a light bug report that looks similar). I'm using a similarly recent build of line_profiler on my linux machine with no crashes.

**Comment by rkern** [comment]
The version number reported with `--version` is an oversight.
