### ISSUE TITLE
"kernprof -l -v sample.py" does not recognize decorator @profile

### ISSUE THREAD

**Issue by altarmobile** [rkern/line_profiler#24]
line_profiler installed in anaconda distribution. %lprun runs fine.
however, when I try to kerprof in the following situation:

# file: primes.py
@profile
def primes(n): 
    if n==2:
        return [2]
    elif n<2:
        return []
    s=range(3,n+1,2)
    mroot = n ** 0.5
    half=(n+1)/2-1
    i=0
    m=3
    while m <= mroot:
        if s[i]:
            j=(m*m-3)/2
            s[j]=0
            while j<half:
                s[j]=0
                j+=m
        i=i+1
        m=2*i+3
    return [2]+[x for x in s if x]

primes(100)

in terminal:
kernprof -l -v primes.py

has the following info:
Wrote profile results to primes.py.lprof
Timer unit: 1e-06 s

Traceback (most recent call last):
  File "/Users/Retina/anaconda/envs/py2k/bin/kernprof", line 9, in <module>
    load_entry_point('line-profiler==1.0', 'console_scripts', 'kernprof')()
  File "build/bdist.macosx-10.5-x86_64/egg/kernprof.py", line 221, in main
  File "primes.py", line 8, in <module>
    @profile
NameError: name 'profile' is not defined

**Comment by rkern** [comment]
Do you have the [future](https://pypi.python.org/pypi/future) package installed? #12

**Comment by altarmobile** [comment]
Thanks fro the quick reply.
yes, future 0.14.3 installed.

the error message is the same. anaconda 2.7 runs on OSX101.10.3

if I removes ‘@profile’, in ipython terminal:

%load_ext line_profiler

%lprun -f primes primes(1000) 

that runs perfectly!

**Comment by Ralph-Wang** [comment]
I got the same traceback message but I didn't install **future**

System: OS X 10.10.3
Python:  2.7.6
