### ISSUE TITLE
profiling unittest.TestCase methods does not execute anything

### ISSUE THREAD

**Issue by marscher** [rkern/line_profiler#27]
``` python
import unittest
class Foo(unittest.TestCase):
       @profile
       def test_me(self):
            print "hi there"
if __name__ == "__main__":
    unittest.main()
```

if invoked with `kernprof -vvl test.py` it correctly shows the code to be profiled, but does not execute anything. Maybe I did something wrong or is this expected not to work?

**Comment by PaulPrice** [comment]
I had the same problem.  It works if I run it under pytest:

    kernprof -l -v pytest test.py
