### ISSUE TITLE
Option to convert 'python -m line_profiler' timer units to seconds

### ISSUE THREAD

**Issue by winny-** [rkern/line_profiler#29]
Some reason I have a tough time counting columns (zeros), so I am wondering if there is an option to convert timer units to seconds when using `python -m line_profiler ...`.

line_profiler has saved me a lot of time, by the way, so keep up the great work!

**Comment by chrisranderson** [comment]
Agreed. As is, I don't get much information out of timer units - I just look at the total time taken by the function and the check the percentages to get a ballpark.

**Comment by caethan** [comment]
Timer units can be specified when running from the magic command instead of through the command line, FYI.

**Comment by winny-** [comment]
Thanks for the feedback. More the reason to use ipython :)

Context from [README.rst](https://github.com/rkern/line_profiler/blob/master/README.rst):

> If you are using IPython, there is an implementation of an %lprun magic command which will let you specify functions to profile and a statement to execute. It will also add its LineProfiler instance into the __builtins__, but typically, you would not use it like that.

Related:

1. https://github.com/rkern/line_profiler/issues/97
2. https://github.com/rkern/line_profiler/issues/136
