### ISSUE TITLE
IPython cell magic

### ISSUE THREAD

**Issue by klonuo** [rkern/line_profiler#31]
Hi,

Changelog includes this line:

> - ENH: Support for IPython cell blocks. Thanks to Michael Forbes for adding this feature.

Does this mean that we can run profiler in Notebook via cell block magic (i.e. profile cell block without making it function), as I don't see that it is currently possible?

Searching for @mforbes I cant see that he contributed to this repo.

Thanks

**Comment by mforbes** [comment]
This was added back to the project [on bitbucket](https://bitbucket.org/robertkern/line_profiler/commits/all).  Somehow this does not seem to have been propegated to github...

**Comment by klonuo** [comment]
Thanks for your quick reply.

**Comment by auneri** [comment]
I've made an attempt at a cell magic [available here](https://gist.github.com/auneri/54600375aa0317b9c47e). It is very hacky, but seems to work.

I could refactor and make a proper pull request if the implementation approach is acceptable, and if there is interest.

**Comment by jdanbrown** [comment]
In case anyone else ends up here, I adapted @auneri's gist into another version that's a bit less code (because it wraps the line magic, which is a hack):
- https://github.com/jdanbrown/potoo/blob/a7cc6a9/potoo/lprun_cell_magic.py
