### ISSUE TITLE
"function declaration isn’t a prototype" during compilation

### ISSUE THREAD

**Issue by socketpair** [rkern/line_profiler#33]
```
unset_trace.h:1:1: warning: function declaration isn’t a prototype [-Wstrict-prototypes]
     void unset_trace();
```

**Comment by mik13ST** [comment]
I just had the same issue when installing with '$ pip install line_profiler'. I managed to notice a "Permission denied" in the error log and after running it as superuser the issue is gone, obviously. Happens when you install python package for the first time :smile:.
