### ISSUE TITLE
NameError: name 'profile' is not defined

### ISSUE THREAD

**Issue by dEvasEnApati** [rkern/line_profiler#35]
Hello

I wrote the following code:

    @profile
    def hello():
      print('Testing')
  
    hello()

And called

    kernprof -l /tmp/hello.py

Here is the output

    Wrote profile results to alignAll.py.lprof
    Traceback (most recent call last):
      File "/usr/local/bin/kernprof", line 9, in <module>
        load_entry_point('line-profiler==1.0', 'console_scripts', 'kernprof')()
      File "/usr/local/lib/python2.7/dist-packages/kernprof.py", line 221, in main
        execfile(script_file, ns, ns)
      File "directPixelBased/alignAll.py", line 9, in <module>
        @profile
    NameError: name 'profile' is not defined

Ubuntu 14.04 with Python 2.7.6

Thanks 
Ajay

**Comment by icoleslaw** [comment]
I'm experiencing the same problem...

**Comment by rkern** [comment]
Please see if #25 solves your problem.

**Comment by dEvasEnApati** [comment]
It does! Thanks.

**Comment by VSZM** [comment]
Just add 
```
import line_profiler
profile = line_profiler.LineProfiler()
```

**Comment by calincru** [comment]
@VSZM thanks, that solved it for me.

@rkern Can this be avoided?  Is it perhaps because the function I'm trying to profile is not in the script that I run but in an imported (locally developed) package?
