### ISSUE TITLE
Error when starting gunicorn with kernprof

### ISSUE THREAD

**Issue by pallix** [rkern/line_profiler#40]
An error occurs when starting a gunicorn server with kernprof:

```
kernprof  -l ./bin/gunicorn --paste etc/development.ini --forwarded-allow-ips="127.0.0.1" -t 6000

Error: gunicorn
Wrote profile results to gunicorn.lprof
```

`gunicorn.lprof` is then empty:

```
cat gunicorn.lprof 
��F�_line_profiler��	LineStats���)}���}�(�unit�G>�����퍌timings�}�ub.⏎ 
```

I'm using `Python 3.4.3`

**Comment by rkern** [comment]
`gunicorn` runs your code in a subprocess which isn't under the control of `kernprof`, so it will never work. From a quick perusal of its documentation, I don't see a flag to tell it to run all in the same process for development purposes (which is fine; that's not its job). You can probably use a simple script that uses [`wsgiref.simple_server.make_server()`](https://docs.python.org/2/library/wsgiref.html#wsgiref.simple_server.make_server) to kick off your app instead when you need to do this profiling.
