### ISSUE TITLE
Set number of times to run function with line_profiler

### ISSUE THREAD

**Issue by jakirkham** [rkern/line_profiler#42]
It might be nice to get some better statistics to set some number of times to run the function like what is done with timeit. This way if there is some drift from run to run it will hopefully cancel out on the average. This would also allow for some error bars to be added. If there is already a way to do this, please let me know.

Also, thanks for such an awesome tool. This is my favorite Python profiling tool by far.

**Comment by rkern** [comment]
If you just run the function a number of times, the timings will all accumulate. `LineProfiler` itself will not do this because it is designed to work _in situ_ and not just for top-level functions.

**Comment by jakirkham** [comment]
Are you meaning that I should use `kernprof` instead?

**Comment by rkern** [comment]
The use of `kernprof` as the runner script is independent of my recommendation here.

Just run the profiled function in a short loop if you need it profiled multiple times:

```
@profile
def f():
    ...

for i in range(10):
    f()
```

However you run `LineProfiler`, through `kernprof`, `%lprun`, or manual API usage, you should be able to do that.

**Comment by jakirkham** [comment]
Ah, ok, thanks for clarifying.

**Comment by jakirkham** [comment]
Though it is easy for me to get something similar by adding some more code on my side, I still think it would be nice to see this as an option for the line profiler.

**Comment by rkern** [comment]
The reasoning I have given still stands. That functionality does not fit with the other requirements for `LineProfiler`.
