### ISSUE TITLE
NameError: name 'profile' is not defined

### ISSUE THREAD

**Issue by mrkafk** [rkern/line_profiler#49]
Yes, I have followed directions in https://github.com/rkern/line_profiler/pull/25

That is, I have installed `future` package and installed `line_profiler` from `master` branch (by running `python setup.py install`).

However, I still get:

	  File "/export/home/myuser/mysite/mysite/views/aview.py", line 207, in <module>
		@profile
	NameError: name 'profile' is not defined

Command:	
	
     kernprof -l -v /export/home/myuser/mysite/ve/bin/pserve development.ini --reload	

System: RHEL 6.3, Python 2.7.10 x64.

**Comment by rkern** [comment]
`pserve` is running your code in a subprocess that `kernprof` doesn't get access to.

**Comment by mrkafk** [comment]
Actually, I found the way to make it work, drop `--reload` option:

    kernprof -l -v ~/mysite/ve/bin/pserve development.ini

**Comment by rkern** [comment]
Great, thanks for investigating further!
