### ISSUE TITLE
NameError: name 'profile' is not defined

### ISSUE THREAD

**Issue by aphearin** [rkern/line_profiler#53]
@rkern - I have recently installed line_profiler using pip, with no apparent problems. I attempt to run the exact trivial test in #35 and run into the exact same error message. #35 refers to #25 as the resolution to the problem, but reading through #25 I do not see where the problem was resolved. I use OS X with python 2.7.11

Traceback (most recent call last):
  File "/Users/aphearin/anaconda/bin/kernprof", line 11, in <module>
    sys.exit(main())
  File "/Users/aphearin/anaconda/lib/python2.7/site-packages/kernprof.py", line 221, in main
    execfile(script_file, ns, ns)
  File "hello_world.py", line 2, in <module>
    @profile
NameError: name 'profile' is not defined

**Comment by Bernhard10** [comment]
The solution mentioned in #25 seems to be only implemented in the master branch, not in the pip package.
Uninstalling the pip version, cloning the git repo and manually running setup.py (requires cython) helps.

**Comment by Nodd** [comment]
@rkern maybe it's time for another release, since this bug keeps appearing in the issues ?

**Comment by aphearin** [comment]
Ahh, ok, yes, thanks, I uninstalled, cloned master 19603402e8686407dd19882fd80764d15b2f8499, ran `python setup.py install`, and then it works as advertised. Thanks @Bernhard10 . I'm now able to use the code, which is great, but I guess I'd like to second @Nodd and suggest considering a new release. Either way, thanks to @rkern for this extremely useful tool.

**Comment by thomasaarholt** [comment]
Hiya, just thought I'd point out that the pip version still hasn't been implemented. Is there a reason for this? I spent a little while trying to figure out what on earth I was doing wrong before realising the fault wasn't with me.

**Comment by thomasaarholt** [comment]
Actually, I have this problem with master as well. I'm calling it using Jupyter Notebook according to the code below. I've inserted `@profile` above the appropriate function, and ran `kernprof -1 filewithfunction.py`

```python
%matplotlib qt4 
%load_ext line_profiler
import hyperspy.api as hs

path = "mypath"
filename = "myfile.test"

%lprun -f hs.load(path+filename)
```
I've tried installing it via `pip install -e ./` and `python setup.py install`, without any difference. 

Any suggestions?

**Comment by caethan** [comment]
New 2.0 release should fix this (reopen if there's still a problem, please).
