### ISSUE TITLE
No output when script uses os._exit(0)

### ISSUE THREAD

**Issue by mszlazak** [rkern/line_profiler#55]
FYI, if you use os._exit(0) on at least Ubuntu 14.04 with Python 3.5.1 then there will be no profiler output on your console with  kernprof -l -v my_script.py my_data.txt.

```
if __name__ == "__main__":
    from os import _exit
    main()
    _exit(0)

```

**Comment by rkern** [comment]
Sorry, nothing we can do about that. `os._exit()` avoids all of the hooks that we could use to run the output code.
