### ISSUE TITLE
sabnzbd - NameError: name 'setup' is not defined

### ISSUE THREAD

**Issue by geoffreymk** [rkern/line_profiler#59]
Hi 

I have installed sabnzbd and sickbeard on my DS112+ and been trying to set up a few things to things get automatically get transcoded once downloaded. 

At the moment i have been having trouble with the following script:

sabToSickBeardwithCoverter.py

It runs but then i get the following error when it does post processing:

> 
>            Trying to install SetupTools
>             Traceback (most recent call last):
>            File "/volume1/Downloads/Scripts/sabToSickBeardwithConverter.py", line 6, in <module>
>            from readSettings import ReadSettings
>             File "/volume1/Downloads/Scripts/readSettings.py", line 9, in <module>
>            setup.ez_setup.main()
>              NameError: name 'setup' is not defined

I have tried to install the setup tool now a few times and it shows as it has downloaded and installed fine but still getting that error on post processing. I am very new to all of this so been googling for last few days but anything i try to install with cmd just doesnt seem to be working. 

Any had same experience?

**Comment by Nodd** [comment]
A `NameError` is likely to indicate a problem in the python file rather than the installation.
Does it have anything to do with line_profiler ?

**Comment by rkern** [comment]
Seems unlikely. Sorry, @geoffreymk I hope you find a solution to your problem!

**Comment by geoffreymk** [comment]
Hi @Nodd , i m not sure what the line_profiler is. Sorry i am very new to all this so dont really know much apart from the set on instructions how to install. If you can explain what the line_profile is would be much appreciated.

**Comment by rkern** [comment]
@geoffreymk `line_profiler` is unrelated to sabnzbd. You ended up here by mistake somehow. I believe that you can get sabnzbd help here: https://forums.sabnzbd.org/

**Comment by geoffreymk** [comment]
Thanks @rkern , apologies for wrong forum!
