### ISSUE TITLE
ImportError: No module named babelfish

### ISSUE THREAD

**Issue by geoffreymk** [rkern/line_profiler#60]
Hi

Anyone seen this error before with readsettings?

` File "/volume1/Downloads/Scripts/readSettings.py", line 11, in <module>
    from babelfish import Language
ImportError: No module named babelfish`

Cant seem to figure out what the issue is, or if i am missing some installation.

I used the following readsetting - https://github.com/mdhiggins/sickbeard_mp4_automator/blob/master/readSettings.py

**Comment by rkern** [comment]
@geoffreymk You are still sending these to the wrong repository somehow.

https://github.com/mdhiggins/sickbeard_mp4_automator/issues
