### ISSUE TITLE
Ship wheels

### ISSUE THREAD

**Issue by techtonik** [rkern/line_profiler#63]
`pip install` complains about missing Visual C++ 9.0. It would be nice if it could fetch compiled wheels to avoid this problem.

**Comment by caethan** [comment]
Released an OSX wheel with 2.0, as that's my main development machine.  I'll see if I can dig up a windows machine to build a Win wheel.

**Comment by techtonik** [comment]
AppVeyor to the rescue - https://packaging.python.org/appveyor/
