### ISSUE TITLE
compile the _line_profiler.o error  under pypy-5.0.1 

### ISSUE THREAD

**Issue by lufeng4828** [rkern/line_profiler#77]
Hi 

when i compile the _line_profiler.o  under pypy-5.0.1 use the command below:

    # pypy --version
    Python 2.7.10 (bbd45126bc691f669c4ebdfbd74456cd274c6b92, Jun 30 2016, 15:15:02)
    [PyPy 5.0.1 with GCC 4.8.5 20150623 (Red Hat 4.8.5-4)]

    # cc -O2 -fPIC -Wimplicit -I/usr/lib64/pypy-5.0.1/include -c _line_profiler.c -o build/temp.linux- x86_64-2.7/_line_profiler.o
    _line_profiler.c: In function ‘__pyx_pf_14_line_profiler_12LineProfiler_12enable’:
    _line_profiler.c:2995:3: warning: implicit declaration of function ‘PyEval_SetTrace’ [-Wimplicit-    function-declaration]
       PyEval_SetTrace(__pyx_f_14_line_profiler_python_trace_callback, ((PyObject *)__pyx_v_self));
       ^
    _line_profiler.c: In function ‘__pyx_f_14_line_profiler_python_trace_callback’:
    _line_profiler.c:4049:33: error: ‘PyTrace_LINE’ undeclared (first use in this function)
       __pyx_t_3 = ((__pyx_v_what == PyTrace_LINE) != 0);
                                 ^
    _line_profiler.c:4049:33: note: each undeclared identifier is reported only once for each function it appears in
    _line_profiler.c:4055:33: error: ‘PyTrace_RETURN’ undeclared (first use in this function)
       __pyx_t_3 = ((__pyx_v_what == PyTrace_RETURN) != 0);

any help appreciated!!!

**Comment by Nodd** [comment]
Pypy doesn't have the same C-api as cpython, so non pure python libraries are not compatible between both implementations.
