### ISSUE TITLE
Installation failure

### ISSUE THREAD

**Issue by Darker** [rkern/line_profiler#78]
```
running install

running build

running build_py

creating build

creating build\lib.win-amd64-3.4

copying line_profiler.py -> build\lib.win-amd64-3.4

copying kernprof.py -> build\lib.win-amd64-3.4

running build_ext

building '_line_profiler' extension

error: Unable to find vcvarsall.bat
```
I get this error when I try to install using `pip`. After that, the installation terminates and the tool is not available.

**Comment by caethan** [comment]
Looks like you need the Visual C++ compiler for Python.  Take a look here: https://www.microsoft.com/en-us/download/details.aspx?id=44266 

Let me know if this fixes the problem.  I'll see if I can dig up a Windows machine to compile a wheel for it, but right now most everything requires compilation on your machine.

**Comment by caethan** [comment]
See also https://github.com/rkern/line_profiler/issues/63

**Comment by Darker** [comment]
I fixed this by downloading the *.whl file from some website. I'll try to install the compiler. Thanks for reply.

**Comment by caethan** [comment]
Mind linking where you got the wheel from?

**Comment by Darker** [comment]
No problem, it's in my home computer's history. When I come home I'll share the link.

**Comment by Rejerh** [comment]
Hi Darker,

did you find where the .whl came from?
Any chance you could write down a quick step through on how to fix this problem?

Thanks a lot

**Comment by Darker** [comment]
Ok, finally found it: http://www.lfd.uci.edu/~gohlke/pythonlibs/
Specifically the file I used: http://www.lfd.uci.edu/~gohlke/pythonlibs/g7ckv9dk/line_profiler-2.0-cp34-cp34m-win_amd64.whl
