### ISSUE TITLE
Installing broke pip and django, and probably a lot of other things.

### ISSUE THREAD

**Issue by eturpin** [rkern/line_profiler#82]
So, I installed line_profiler with `sudo pip3 install line_profiler` on Ubuntu 14.04.5 LTS, then tried to run a django application. Application would not run (using `python3 manage.py runserver`). So, I attempted fix the system by uninstalling line_profiler, but pip is broken too! Just running `sudo pip3` gives me:

`Traceback (most recent call last):
  File "/usr/bin/pip3", line 5, in <module>
    from pkg_resources import load_entry_point
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 72, in <module>
    import packaging.requirements
  File "/usr/local/lib/python3.4/dist-packages/packaging/requirements.py", line 59, in <module>
    MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
TypeError: __call__() missing 1 required positional argument: 'name'`

Right now, I'd just like to get my system working again. Any ideas?

**Comment by SimonBarendse** [comment]
@eturpin http://stackoverflow.com/questions/41829550/how-to-fix-pip-being-proken-after-installing-line-profiler
upgrading pyparsing worked for me.

**Comment by caethan** [comment]
Looks like not a line_profiler issue.
