### ISSUE TITLE
Missing manpage for kernprof executable

### ISSUE THREAD

**Issue by ghisvail** [rkern/line_profiler#83]
It is a recommended practice in the Linux community to provide corresponding manpages to publicly installed command-line executables. `line_profiler` installs the `kernprof` commands, which lacks a manpage currently.

The solution could be as simple as providing a corresponding `kernprof.1.md` or `kernprof.1.rst` with a plain text formatted manpage, and let Linux distributions run `pandoc` to convert it to a manpage and install it wherever appropriate.

**Comment by rkern** [comment]
Would you care to contribute one?
