### ISSUE TITLE
If the file is coded in utf-8, @profile will be not defined

### ISSUE THREAD

**Issue by gy20073** [rkern/line_profiler#86]
I found a bug when the top of the python source file has the line:
"# -*- coding: utf-8 -*-"
the @profile decorator will not work (profile not defined)

I could remove the top line to make this work, but it would be nice to fix this bug

**Comment by rkern** [comment]
I cannot replicate this. Can you provide a minimal example file that demonstrates the problem? Please also provide the command line that you used.

**Comment by caethan** [comment]
Cannot replicate
