### ISSUE TITLE
line_profiler runtime issues in default install

### ISSUE THREAD

**Issue by ek-nath** [rkern/line_profiler#94]
`conda install -c anaconda line_profiler=2.0` works but `conda install line_profiler`'s installation succeeds. However, neither the console version nor the jupyter version work.
But "Don't work", I mean, I get the following output: `Could not extract a code object for the object None`

python version: 3.6
windows 10 x64

**Comment by GiorgioBalestrieri** [comment]
Same issue here, using Jupyter with Python 3.6

**Comment by fahall** [comment]
I had the same issue when I used:

`%lprun -f function_to_profile()`

Fixed by running:
`%lprun -f function_to_profile function_to_profile()

Unfortunately, in Python3.6 w/ Jupyter, I am not getting any output from this.

**Comment by superquest** [comment]
@fahall That worked for me

**Comment by caethan** [comment]
This is a user error.  The format is 

`%lprun -f FUNCTION_TO_PROFILE CODE_EXPRESSION_TO_RUN`

In most cases the function to profile and the expression to run will be very similar, but not in all cases.  Both are still required.
